name: board_game_moongi
version: 1.0.0+1
publish_to: 'none'

description: A high-performance, offline-first hybrid Android application featuring classic board games.

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^9.1.1
  
  # Local Storage
  path_provider: ^2.1.1
  
  # Animations
  flutter_animate: ^4.2.0+1
  rive: ^0.13.20
  
  # Navigation
  go_router: ^16.2.1
  
  # UI Components
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  
  # Utilities
  equatable: ^2.0.5
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  
  # Audio & Haptics
  audioplayers: ^6.5.1
  vibration: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # assets:
    # - assets/images/
    # - assets/animations/
    # - assets/sounds/
    # - assets/fonts/
  
